export const GET_ALL_WEBTOONS_FULLFILLED = 'GET_ALL_WEBTOONS_FULLFILLED';
export const GET_ALL_WEBTOONS_PENDING = 'GET_ALL_WEBTOONS_PENDING';
export const GET_ALL_WEBTOONS_REJECTED = 'GET_ALL_WEBTOONS_REJECTED';

export const GET_FAV_WEBTOON = 'GET_FAV_WEBTOON';
export const POST_FAV_WEBTOON = 'POST_FAV_WEBTOON';
export const DELETE_FAV_WEBTOON = 'DELETE_FAV_WEBTOON';

export const GET_FAVS_PENDING = 'GET_FAVS_PENDING';
export const GET_FAVS_FULFILLED = 'GET_FAVS_FULFILLED';
export const GET_FAVS_REJECTED = 'GET_FAVS_REJECTED';
export const POST_FAV_PENDING = 'POST_FAV_PENDING';
export const POST_FAV_FULFILLED = 'POST_FAV_FULFILLED';
export const POST_FAV_REJECTED = 'POST_FAV_REJECTED';
export const DEL_FAV_PENDING = 'DEL_FAV_PENDING';
export const DEL_FAV_FULFILLED = 'DEL_FAV_FULFILLED';
export const DEL_FAV_REJECTED = 'DEL_FAV_REJECTED';

export const GET_EPISODES_PENDING = 'GET_EPISODES_PENDING';
export const GET_EPISODES_FULLFILLED = 'GET_EPISODES_FULLFILLED';
export const GET_EPISODES_REJECTED = 'GET_EPISODES_REJECTED';

export const GET_PAGES_PENDING = 'GET_PAGES_PENDING';
export const GET_PAGES_FULLFILLED = 'GET_PAGES_FULLFILLED';
export const GET_PAGES_REJECTED = 'GET_PAGES_REJECTED';

export const GET_PROFILE_PENDING = 'GET_PROFILE_PENDING';
export const GET_PROFILE_FULLFILLED = 'GET_PROFILE_FULLFILLED';
export const GET_PROFILE_REJECTED = 'GET_PROFILE_REJECTED';

export const GET_METHOD = 'GET_METHOD';
export const PUT_METHOD = 'PUT_METHOD';
